#include "clue/game_service.h"
#include <iostream>

namespace Clue {

GameServiceImpl::GameServiceImpl() : game(std::make_shared<Game>()) {}

grpc::Status GameServiceImpl::CreateGame(grpc::ServerContext* context, const clue::CreateGameRequest* request, clue::GameStatus* response) {
    std::lock_guard<std::mutex> lock(gameMutex);

    std::vector<std::string> names;
    for (const auto& name : request->player_names()) {
        names.push_back(name);
    }

    std::set<Card> myHand;
    for (const auto& card : request->my_hand()) {
        // Map proto card to internal card
        // Assuming integer values match or using string conversion if needed.
        // SmartEnum usually works with integer indices if they match.
        // Let's assume direct cast works if we aligned them.
        // Check alignment:
        // Proto: CARD_MISS_SCARLET = 1
        // SmartEnum: ENUM_MEMBER(MISS_SCARLET) -> likely 1 if NONE is 0
        // We need to be careful. SmartEnum assigns 0 to FIRST, etc?
        // Let's look at constants.h again.
        // BEGIN_SMART_ENUM(Card) ENUM_MEMBER(NONE) ...
        // It seems typically it starts at 0.
        // So static_cast<Card::Value>(card) might work.
        // But Card is a class generated by SmartEnum.
        // Card c = (Card::Value)card;

        // Actually SmartEnum usually creates an enum class named Value inside.
        myHand.insert(static_cast<Card::Value>(card));
    }

    game->createGame(names, myHand);

    if (!request->who_goes_first().empty()) {
        try {
            game->setWhoGoesFirst(request->who_goes_first());
        } catch (...) {
            return grpc::Status(grpc::StatusCode::INVALID_ARGUMENT, "Invalid starting player");
        }
    }

    *response = game->toProto();
    return grpc::Status::OK;
}

grpc::Status GameServiceImpl::SubmitTurn(grpc::ServerContext* context, const clue::Turn* request, clue::GameStatus* response) {
    std::lock_guard<std::mutex> lock(gameMutex);

    try {
        // Construct internal Turn object from Proto Turn
        // This requires mapping all fields back.
        // Since Turn constructor is complex, we might need to look up players.

        std::shared_ptr<Player> playersTurn = game->getPlayerByName(request->players_turn_name());
        std::shared_ptr<Player> playerAnswered = nullptr;
        if (!request->player_answered_name().empty()) {
             playerAnswered = game->getPlayerByName(request->player_answered_name());
        }

        std::set<std::shared_ptr<Player>> playersWithoutCards;
        for (const auto& name : request->players_without_cards_names()) {
            playersWithoutCards.insert(game->getPlayerByName(name));
        }

        std::shared_ptr<Turn> turn = std::make_shared<Turn>(
            playersTurn,
            request->suggestion_made(),
            static_cast<Suspect::Value>(request->suggestion_suspect()),
            static_cast<Weapon::Value>(request->suggestion_weapon()),
            static_cast<Room::Value>(request->suggestion_room()),
            playerAnswered,
            static_cast<Card::Value>(request->card_shown()),
            playersWithoutCards
        );

        // We need to handle "isMyTurn" and "iAnswered" but Turn constructor logic in original code
        // might infer some of this or we pass it?
        // Original Turn constructor signature:
        /*
        explicit Turn(
            std::shared_ptr<Player> playersTurnIn,
            bool accusationMadeIn,
            Suspect suspectAccusedIn,
            Weapon weaponAccusedIn,
            Room roomAccusedIn,
            std::shared_ptr<Player> playerAnsweredIn,
            Card cardShownIn,
            const std::set<std::shared_ptr<Player>>& playersWithoutCards
            );
        */
        // It doesn't take isMyTurn or iAnswered. It calculates them?
        // Let's check Turn.cpp if we can. Or just trust it.
        // Wait, I saw Turn.h.
        // private: bool isMyTurn = false;
        // logic is likely inside constructor or executeTurn.

        game->submitTurn(turn);

        *response = game->toProto();
        return grpc::Status::OK;
    } catch (const std::exception& e) {
        return grpc::Status(grpc::StatusCode::INTERNAL, e.what());
    }
}

grpc::Status GameServiceImpl::GetGameState(grpc::ServerContext* context, const clue::Empty* request, clue::GameStatus* response) {
    std::lock_guard<std::mutex> lock(gameMutex);
    *response = game->toProto();
    return grpc::Status::OK;
}

grpc::Status GameServiceImpl::GetPlayer(grpc::ServerContext* context, const clue::PlayerRequest* request, clue::Player* response) {
    std::lock_guard<std::mutex> lock(gameMutex);
    try {
        auto player = game->getPlayerByName(request->name());
        // Map player to proto
        response->set_name(player->getName());
        response->set_num_cards_in_hand(player->getNumCardsInHand());
        response->set_solved(player->isPlayerSolved());
        for (const auto& card : *player->getHand()) {
            response->add_hand(static_cast<clue::Card>(card.Value()));
        }
         for (const auto& card : *player->getNotInHand()) {
            response->add_not_in_hand(static_cast<clue::Card>(card.Value()));
        }
        return grpc::Status::OK;
    } catch (const Game::PlayerNotFoundByName&) {
        return grpc::Status(grpc::StatusCode::NOT_FOUND, "Player not found");
    }
}

} // namespace Clue
