name: CMake

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CCACHE_DIR: ${{ github.workspace }}/.ccache

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ninja-build ccache

    - name: Setup ccache
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.ccache
        # KEY: Always unique so we SAVE the new cache at the end of this run
        key: ${{ runner.os }}-ccache-${{ github.ref_name }}-${{ github.sha }}

        # RESTORE KEYS: The "Waterfall" logic
        # GitHub searches these prefixes in order.
        restore-keys: |
          ${{ runner.os }}-ccache-${{ github.ref_name }}-
          ${{ runner.os }}-ccache-dev-
          ${{ runner.os }}-ccache-master-
          ${{ runner.os }}-ccache-

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Ccache Stats
      run: ccache -s
